config/routes.rb
ProblemReport::Application.routes.draw do

  resources :attachments

  root :to => 'visitor#index'

  resources :statuses

  resources :priorities

  resources :follow_junctions

  resources :work_on_junctions

  resources :problem_report_emails

  resources :problem_report_histories

  resources :problem_report_notes

  resources :escalations

  resources :systems

  resources :categories

  resources :problem_types

  resources :positions

  resources :users

  resources :problem_report_records

  match 'users/login/:id', to: 'users#login', via: :post
  match 'users/logout/', to: 'users#logout', via: :post

  match 'home', to: 'home#index', via: :get
  match 'updateWorkingOnTable/', to: 'home#updateWorkingOnTable', via: :get
  match 'updateAllReportsTable/', to: 'home#updateAllReportsTable', via: :get
  match 'updateFollowReportsTable/', to: 'home#updateFollowReportsTable', via: :get
  match 'updateUnClaimedReportsTable/', to: 'home#updateUnClaimedReportsTable', via: :get
  match 'workOnReport/', to: 'home#workOnReport', via: :post
  match 'quitWorkingOnReport/', to: 'home#quitWorkingOnReport', via: :delete
  match 'followReport/', to: 'home#followReport', via: :post
  match 'unfollowReport/', to: 'home#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'home#requestAssigningForm', via: :get
  match 'assignProblemReports', to:'home#assignProblemReports', via: :put
  match 'clearNotification', to:'home#clearNotification', via: :put

  match 'requestNoteToModify', to: 'problem_report_records#requestNoteToModify', via: :post
  match 'modifyNote', to: 'problem_report_records#modifyNote', via: :put
  match 'initializeStatus', to: 'problem_report_records#initializeStatus',via: :post
  match 'sendEmail', to: 'problem_report_records#sendEmail', via: :post

  match 'addNewNote', to:'problem_report_records#addNewNote', via: :post
  match 'visitor/', to: 'visitor#index', via: :get

  match "search" => "problem_report_records#index", :via => :get
  match 'updateWorkingOnTable/', to: 'problem_report_records#updateAllReportsTable', via: :get
  match 'workOnReport/', to: 'problem_report_records#workOnReport', via: :post
  match 'followReport/', to: 'problem_report_records#followReport', via: :post
  match 'unfollowReport/', to: 'problem_report_records#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'problem_report_records#requestAssigningForm', via: :get
  match 'quitWorkingOnReport/', to:'problem_report_records#quitWorkingOnReport', via: :delete

  match "report" => "report#index", :via => :get

  match "configuration" => "configuration#index", :via => :get

end

app/models/escalation.rb
class Escalation < ActiveRecord::Base
	attr_accessible :name, :id, :created_at, :updated_at

	has_many :problem_report_records

	validates :name, :presence => true

	before_destroy do |escalation|
		count = escalation.problem_report_records.count
		if(count != 0)
			escalation.errors[:id] = "Cannot delete escalation #{escalation.name}, #{count} Problem Report Records have this escalation."
			false
		end
	end
	
end

app/controllers/escalations_controller.rb
class EscalationsController < ApplicationController
  before_filter :authenticateAdmin
  # GET /escalations
  # GET /escalations.json
  def index
    @escalations = Escalation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @escalations }
    end
  end

  # GET /escalations/1
  # GET /escalations/1.json
  def show
    @escalation = Escalation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @escalation }
    end
  end

  # GET /escalations/new
  # GET /escalations/new.json
  def new
    @escalation = Escalation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @escalation }
    end
  end

  # GET /escalations/1/edit
  def edit
    @escalation = Escalation.find(params[:id])
  end

  # POST /escalations
  # POST /escalations.json
  def create
    @escalation = Escalation.new(params[:escalation])

    respond_to do |format|
      if @escalation.save
        format.html { redirect_to @escalation, notice: 'Escalation was successfully created.' }
        format.json { render json: @escalation, status: :created, location: @escalation }
      else
        format.html { render action: "new" }
        format.json { render json: @escalation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /escalations/1
  # PUT /escalations/1.json
  def update
    @escalation = Escalation.find(params[:id])

    respond_to do |format|
      if @escalation.update_attributes(params[:escalation])
        format.html { redirect_to @escalation, notice: 'Escalation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @escalation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escalations/1
  # DELETE /escalations/1.json
  def destroy
    @escalation = Escalation.find(params[:id])
    @escalation.destroy

    respond_to do |format|
      format.html { redirect_to escalations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/escalations_helper.rb
module EscalationsHelper
end

app/views/escalations/_form.html.erb
<%= form_for(@escalation) do |f| %>
  <% if @escalation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@escalation.errors.count, "error") %> prohibited this escalation from being saved:</h2>

      <ul>
      <% @escalation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/escalations/edit.html.erb
<h1>Editing escalation</h1>

<%= render 'form' %>

<%= link_to 'Show', @escalation %> |
<%= link_to 'Back', escalations_path %>

app/views/escalations/index.html.erb
<h1>Listing escalations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @escalations.each do |escalation| %>
  <tr>
    <td><%= escalation.name %></td>
    <td><%= link_to 'Show', escalation %></td>
    <td><%= link_to 'Edit', edit_escalation_path(escalation) %></td>
    <td><%= link_to 'Destroy', escalation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Escalation', new_escalation_path %>

app/views/escalations/new.html.erb
<h1>New escalation</h1>

<%= render 'form' %>

<%= link_to 'Back', escalations_path %>

app/views/escalations/show.html.erb
<p>
  <b>Name:</b>
  <%= @escalation.name %>
</p>


<%= link_to 'Edit', edit_escalation_path(@escalation) %> |
<%= link_to 'Back', escalations_path %>