config/routes.rb
ProblemReport::Application.routes.draw do

  resources :attachments

  root :to => 'visitor#index'

  resources :statuses

  resources :priorities

  resources :follow_junctions

  resources :work_on_junctions

  resources :problem_report_emails

  resources :problem_report_histories

  resources :problem_report_notes

  resources :escalations

  resources :systems

  resources :categories

  resources :problem_types

  resources :positions

  resources :users

  resources :problem_report_records

  match 'users/login/:id', to: 'users#login', via: :post
  match 'users/logout/', to: 'users#logout', via: :post

  match 'home', to: 'home#index', via: :get
  match 'updateWorkingOnTable/', to: 'home#updateWorkingOnTable', via: :get
  match 'updateAllReportsTable/', to: 'home#updateAllReportsTable', via: :get
  match 'updateFollowReportsTable/', to: 'home#updateFollowReportsTable', via: :get
  match 'updateUnClaimedReportsTable/', to: 'home#updateUnClaimedReportsTable', via: :get
  match 'workOnReport/', to: 'home#workOnReport', via: :post
  match 'quitWorkingOnReport/', to: 'home#quitWorkingOnReport', via: :delete
  match 'followReport/', to: 'home#followReport', via: :post
  match 'unfollowReport/', to: 'home#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'home#requestAssigningForm', via: :get
  match 'assignProblemReports', to:'home#assignProblemReports', via: :put
  match 'clearNotification', to:'home#clearNotification', via: :put

  match 'requestNoteToModify', to: 'problem_report_records#requestNoteToModify', via: :post
  match 'modifyNote', to: 'problem_report_records#modifyNote', via: :put
  match 'initializeStatus', to: 'problem_report_records#initializeStatus',via: :post
  match 'sendEmail', to: 'problem_report_records#sendEmail', via: :post

  match 'addNewNote', to:'problem_report_records#addNewNote', via: :post
  match 'visitor/', to: 'visitor#index', via: :get

  match "search" => "problem_report_records#index", :via => :get
  match 'updateWorkingOnTable/', to: 'problem_report_records#updateAllReportsTable', via: :get
  match 'workOnReport/', to: 'problem_report_records#workOnReport', via: :post
  match 'followReport/', to: 'problem_report_records#followReport', via: :post
  match 'unfollowReport/', to: 'problem_report_records#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'problem_report_records#requestAssigningForm', via: :get
  match 'quitWorkingOnReport/', to:'problem_report_records#quitWorkingOnReport', via: :delete

  match "report" => "report#index", :via => :get

  match "configuration" => "configuration#index", :via => :get

end

app/models/follow_junction.rb
class FollowJunction < ActiveRecord::Base
	attr_accessible :follower_id , :report_followed_id , :last_viewed

	belongs_to :follower, class_name: "User"
	belongs_to :report_followed ,class_name: "ProblemReportRecord"

	validates :follower_id, :presence => true
	validates :report_followed_id, :presence => true
	validates :last_viewed, :presence => true
end

app/controllers/follow_junctions_controller.rb
class FollowJunctionsController < ApplicationController
  # GET /follow_junctions
  # GET /follow_junctions.json
  before_filter :authenticate
  def index
    @follow_junctions = FollowJunction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @follow_junctions }
    end
  end

  # GET /follow_junctions/1
  # GET /follow_junctions/1.json
  def show
    @follow_junction = FollowJunction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follow_junction }
    end
  end

  # GET /follow_junctions/new
  # GET /follow_junctions/new.json
  def new
    @follow_junction = FollowJunction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follow_junction }
    end
  end

  # GET /follow_junctions/1/edit
  def edit
    @follow_junction = FollowJunction.find(params[:id])
  end

  # POST /follow_junctions
  # POST /follow_junctions.json
  def create
    @follow_junction = FollowJunction.new(params[:follow_junction])

    respond_to do |format|
      if @follow_junction.save
        format.html { redirect_to @follow_junction, notice: 'Follow junction was successfully created.' }
        format.json { render json: @follow_junction, status: :created, location: @follow_junction }
      else
        format.html { render action: "new" }
        format.json { render json: @follow_junction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /follow_junctions/1
  # PUT /follow_junctions/1.json
  def update
    @follow_junction = FollowJunction.find(params[:id])

    respond_to do |format|
      if @follow_junction.update_attributes(params[:follow_junction])
        format.html { redirect_to @follow_junction, notice: 'Follow junction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follow_junction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follow_junctions/1
  # DELETE /follow_junctions/1.json
  def destroy
    @follow_junction = FollowJunction.find(params[:id])
    @follow_junction.destroy

    respond_to do |format|
      format.html { redirect_to follow_junctions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/follow_junctions_helper.rb
module FollowJunctionsHelper
end

app/views/follow_junctions/_form.html.erb
<%= form_for(@follow_junction) do |f| %>
  <% if @follow_junction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow_junction.errors.count, "error") %> prohibited this follow_junction from being saved:</h2>

      <ul>
      <% @follow_junction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br />
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :report_followed_id %><br />
    <%= f.number_field :report_followed_id %>
  </div>
  <div class="field">
    <%= f.label :last_viewed %><br />
    <%= f.datetime_select :last_viewed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follow_junctions/edit.html.erb
<h1>Editing follow_junction</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow_junction %> |
<%= link_to 'Back', follow_junctions_path %>

app/views/follow_junctions/index.html.erb
<h1>Listing follow_junctions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Problem report record</th>
    <th>Last viewed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follow_junctions.each do |follow_junction| %>
  <tr>
    <td><%= follow_junction.follower_id %></td>
    <td><%= follow_junction.report_followed_id %></td>
    <td><%= follow_junction.last_viewed %></td>
    <td><%= link_to 'Show', follow_junction %></td>
    <td><%= link_to 'Edit', edit_follow_junction_path(follow_junction) %></td>
    <td><%= link_to 'Destroy', follow_junction, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow junction', new_follow_junction_path %>

app/views/follow_junctions/new.html.erb
<h1>New follow_junction</h1>

<%= render 'form' %>

<%= link_to 'Back', follow_junctions_path %>

app/views/follow_junctions/show.html.erb
<p>
  <b>User:</b>
  <%= @follow_junction.follower_id %>
</p>

<p>
  <b>Problem report record:</b>
  <%= @follow_junction.report_followed_id %>
</p>

<p>
  <b>Last viewed:</b>
  <%= @follow_junction.last_viewed %>
</p>


<%= link_to 'Edit', edit_follow_junction_path(@follow_junction) %> |
<%= link_to 'Back', follow_junctions_path %>