config/routes.rb
ProblemReport::Application.routes.draw do

  resources :attachments

  root :to => 'visitor#index'

  resources :statuses

  resources :priorities

  resources :follow_junctions

  resources :work_on_junctions

  resources :problem_report_emails

  resources :problem_report_histories

  resources :problem_report_notes

  resources :escalations

  resources :systems

  resources :categories

  resources :problem_types

  resources :positions

  resources :users

  resources :problem_report_records

  match 'users/login/:id', to: 'users#login', via: :post
  match 'users/logout/', to: 'users#logout', via: :post

  match 'home', to: 'home#index', via: :get
  match 'updateWorkingOnTable/', to: 'home#updateWorkingOnTable', via: :get
  match 'updateAllReportsTable/', to: 'home#updateAllReportsTable', via: :get
  match 'updateFollowReportsTable/', to: 'home#updateFollowReportsTable', via: :get
  match 'updateUnClaimedReportsTable/', to: 'home#updateUnClaimedReportsTable', via: :get
  match 'workOnReport/', to: 'home#workOnReport', via: :post
  match 'quitWorkingOnReport/', to: 'home#quitWorkingOnReport', via: :delete
  match 'followReport/', to: 'home#followReport', via: :post
  match 'unfollowReport/', to: 'home#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'home#requestAssigningForm', via: :get
  match 'assignProblemReports', to:'home#assignProblemReports', via: :put
  match 'clearNotification', to:'home#clearNotification', via: :put

  match 'requestNoteToModify', to: 'problem_report_records#requestNoteToModify', via: :post
  match 'modifyNote', to: 'problem_report_records#modifyNote', via: :put
  match 'initializeStatus', to: 'problem_report_records#initializeStatus',via: :post
  match 'sendEmail', to: 'problem_report_records#sendEmail', via: :post

  match 'addNewNote', to:'problem_report_records#addNewNote', via: :post
  match 'visitor/', to: 'visitor#index', via: :get

  match "search" => "problem_report_records#index", :via => :get
  match 'updateWorkingOnTable/', to: 'problem_report_records#updateAllReportsTable', via: :get
  match 'workOnReport/', to: 'problem_report_records#workOnReport', via: :post
  match 'followReport/', to: 'problem_report_records#followReport', via: :post
  match 'unfollowReport/', to: 'problem_report_records#unfollowReport', via: :delete
  match 'requestAssigningForm', to:'problem_report_records#requestAssigningForm', via: :get
  match 'quitWorkingOnReport/', to:'problem_report_records#quitWorkingOnReport', via: :delete

  match "report" => "report#index", :via => :get

  match "configuration" => "configuration#index", :via => :get

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	has_attached_file :file

	belongs_to :problem_report_record
	belongs_to :problem_report_email

	def url
		if(!self.file.nil?)
			self.file.url
		end
	end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_filter :authenticate
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])
    @ticket_id = @attachment.problem_report_record_id
    @problem_report_record = ProblemReportRecord.find(@attachment.problem_report_record_id)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
        format.js {}
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @problem_report_record = ProblemReportRecord.find(@attachment.problem_report_record_id)
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
      format.js {}
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :file %><br />
  <%= f.file_field :file %>
  <%= f.label :problem_report_record_id %>
  <%= f.text_field :problem_report_record_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/create.js.erb
$('#new-attachment').dialog('close');
$('#new-attachment').html("<%= escape_javascript( render :partial =>'problem_report_records/new_attachment_form', :locals => {:problem_report_record_id => @ticket_id}) %> ");
$('#attachments').html("<%= escape_javascript( render :partial =>'problem_report_records/attachments', :locals => {:attachments => @problem_report_record.attachments}) %> ");

app/views/attachments/destroy.js.erb
$('#attachments').html("<%= escape_javascript( render :partial =>'problem_report_records/attachments', :locals => {:attachments => @problem_report_record.attachments}) %> ");

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>